### ISSUE TITLE
Consultations package does not create log files

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#104]
When importing business data into consultations, the load encounters and error when trying to write to a  log file because the folder does not exist:

Time to import_business_data = 0:05:20.671009
***** Errors occured during import. Some data may not have been imported. For more information, check resource import error log: /Users/dwuthrich/arches/arches_projects/consultations_prj/consultations_prj/logs/resource_import.log
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dwuthrich/arches/arches4/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/dwuthrich/arches/arches4/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dwuthrich/arches/arches4/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dwuthrich/arches/arches4/ENV/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/dwuthrich/arches/arches4/arches/management/commands/packages.py", line 251, in handle
    force=options['yes'])
  File "/Users/dwuthrich/arches/arches4/arches/management/commands/packages.py", line 1005, in import_business_data
    use_multiprocessing=use_multiprocessing)
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/resources/importer.py", line 203, in import_business_data
    reader.report_errors()
  File "/Users/dwuthrich/arches/arches4/arches/app/utils/data_management/resources/formats/format.py", line 163, in report_errors
    f = open(settings.RESOURCE_IMPORT_LOG, 'w')
IOError: [Errno 2] No such file or directory: '/Users/dwuthrich/arches/arches_projects/consultations_prj/consultations_prj/logs/resource_import.log'

**Comment by dwuthrich** [comment]
meets requirements
