### ISSUE TITLE
Photo widget does not upload files

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#376]
In the latest, the photo widget does not upload files but indicates the tile as un-saved: https://recordit.co/pwg7hLyOar

**Comment by chiatt** [comment]
This is working on my instance. @whatisgalen, can you try to reproduce this bug?

**Comment by dwuthrich** [comment]
@chiatt @whatisgalen I'm still seeing this issue.  Can we resolve this before I demo workflows to HE next week?

**Comment by chiatt** [comment]
Hey @dwuthrich, can you check to see if you are getting any javascript or python errors?

**Comment by dwuthrich** [comment]
@chiatt Here's the error I get:

2019-10-30 16:41:37,119 arches.app.views.tile ERROR    Saving tile failed [Tile id: ]                      [Exception message: TypeError]                      [Exception trace: Traceback (most recent call last):
  File "/Users/dwuthrich/arches/arches4/arches/app/views/tile.py", line 128, in post
    tile.save(request=request)
  File "/Users/dwuthrich/arches/arches4/arches/app/models/tile.py", line 339, in save
    self.validate([])
  File "/Users/dwuthrich/arches/arches4/arches/app/models/tile.py", line 259, in validate
    error = datatype.validate(value, node=node)
  File "/Users/dwuthrich/arches/arches4/arches/app/datatypes/datatypes.py", line 968, in validate
    limit = config['maxFiles']
TypeError: 'NoneType' object is not subscriptable
]
Internal Server Error: /tile

**Comment by dwuthrich** [comment]
meets requirements
