### ISSUE TITLE
Search page and Resource editor language code error

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-her#545]
Term searches in the search page fail and the the resource editor each throw the following error in the django console:

Internal Server Error: /concepts/get_pref_label
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwuthrich/arches/arches5/arches/app/views/concept.py", line 394, in get_pref_label
    label = get_preflabel_from_valueid(valueid, request.LANGUAGE_CODE)
AttributeError: 'WSGIRequest' object has no attribute 'LANGUAGE_CODE'

**Comment by chiatt** [comment]
Closing as I'm not seeing this error. It was likely due to a customization that has been removed.
