### ISSUE TITLE
Package installation error related to sql

### ISSUE THREAD

**Issue by EnisBerk** [archesproject/arches-her#658]
Using Python 3.7.10, and postgres (PostgreSQL) 12.7 (Ubuntu 12.7-1.pgdg20.04+1)

1) installed the master branch of arches-her
2) installed arches stable/5.2.x 
3) install pkg with following command
`python manage.py packages -o load_package -s ./arches_her/pkg -db`

I get the following error 
```
loading concepts
0% [██                            ] 100% | ETA: 00:05:37 | Item ID: Administrative_Area_Type_20200127.xml          Traceback (most recent call last):
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SyntaxError: syntax error at or near "en"
LINE 1: ... = E'altLabel', "value" = E'A\', "languageid" = E'en' WHERE ...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/root/archesrepo/arches/management/commands/packages.py", line 322, in handle
    defer_indexing,
  File "/root/archesrepo/arches/management/commands/packages.py", line 891, in load_package
    load_concepts(package_location, overwrite_concepts, stage_concepts, defer_indexing)
  File "/root/archesrepo/arches/management/commands/packages.py", line 619, in load_concepts
    self.import_reference_data(path, overwrite, stage, defer_indexing)
  File "/root/archesrepo/arches/management/commands/packages.py", line 1015, in import_reference_data
    ret = skos.save_concepts_from_skos(rdf, overwrite, stage, prevent_indexing)
  File "/root/archesrepo/arches/app/utils/skos.py", line 276, in save_concepts_from_skos
    node.save()
  File "/root/archesrepo/arches/app/models/concept.py", line 269, in save
    value.save()
  File "/root/archesrepo/arches/app/models/concept.py", line 1334, in save
    value.save()
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/venvs/archesenv37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "en"
LINE 1: ... = E'altLabel', "value" = E'A\', "languageid" = E'en' WHERE ...
```

**Comment by mradamcox** [comment]
@chiatt suggests commenting these lines out of the preliminary sql file:

```
SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
```
